# Generated by Django 3.1.3 on 2020-11-30 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0008_db_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='mock_res',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
