# Generated by Django 3.1.3 on 2020-12-15 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0010_db_project_header'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='public_header',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
