# Generated by Django 3.1.3 on 2020-12-22 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0012_db_host'),
    ]

    operations = [
        migrations.CreateModel(
            name='DB_project_host',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_id', models.CharField(max_length=100, null=True)),
                ('name', models.CharField(max_length=20, null=True)),
                ('host', models.TextField(null=True)),
            ],
        ),
    ]
