# Generated by Django 3.1.3 on 2021-01-11 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0014_db_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='db_login',
            name='api_body',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='db_login',
            name='body_method',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
