# Generated by Django 3.1.3 on 2021-02-20 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyApp', '0015_auto_20210111_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='db_step',
            name='api_login',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
